import os
import json

def generate_icon_map():
    try:
        # codepoints 文件路径
        codepoints_path = os.path.join(
            os.path.dirname(__file__), 
            'icons', 
            'codepoints'
        )
        
        icon_map = {}
        
        # 读取并解析 codepoints 文件
        with open(codepoints_path, 'r', encoding='utf-8') as f:
            for line in f:
                name, code = line.strip().split(' ')
                # 转换十六进制到 Unicode 字符
                icon_map[name] = chr(int(code, 16))
        
        # 生成 Python 代码
        output_path = os.path.join(
            os.path.dirname(__file__),
            'icon_map.py'
        )
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('#Offical Icon Map from Google Material Icons\n')
            f.write('#Auto Generated by generate_icon_map.py By ZZBuAoYe\n\n')
            f.write('ICON_MAP = {\n')
            for name, unicode_char in icon_map.items():
                f.write(f"    '{name}': '\\u{ord(unicode_char):04x}',\n")
            f.write('}\n')
            
        print(f"成功生成图标映射，包含 {len(icon_map)} 个图标")
        return True
        
    except Exception as e:
        print(f"生成图标映射失败: {str(e)}")
        return False

if __name__ == '__main__':
    generate_icon_map() 